const Homepage = () => {
  return (
    <div className="text-white text-lg absolute top-36 px-24">
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ratione, atque. Deleniti, rerum corrupti! Corporis magnam eos sint cumque eum beatae nesciunt, adipisci id repellat blanditiis quo enim asperiores doloremque rerum sunt impedit doloribus illum consequatur reiciendis voluptas pariatur officia. Voluptates quasi culpa consequuntur impedit cum neque praesentium aperiam maiores ullam totam, ad nulla, blanditiis asperiores deleniti quis est facilis quae distinctio repellendus labore tempore enim repudiandae! Optio rerum, nulla modi veritatis, architecto, quos ipsa alias nemo error a aut. Facilis sequi, error quos consequatur nesciunt odit neque non omnis? Dolorem, similique harum aliquid fugit maxime soluta aut eligendi suscipit distinctio dolore earum amet placeat reprehenderit voluptates vitae natus quidem perferendis. Placeat repudiandae optio qui nisi rem consequatur deleniti nam eligendi. Id aspernatur inventore sint ullam rerum iure qui! Ducimus, eveniet esse temporibus qui ab ex iste quasi et facere hic harum ratione, maiores tempore veniam quis optio nesciunt laudantium, veritatis beatae! Iure, cumque atque, illo eius placeat enim sunt ipsam dolorem reiciendis sequi laborum voluptatem. Veritatis aut, maiores dolorem aliquam recusandae quo. Placeat porro explicabo tempora. Explicabo vero minima quisquam fugit facere, earum nesciunt velit, cum, ipsam aperiam reiciendis? Aliquam, quos! Eaque commodi ratione explicabo consectetur nemo doloribus suscipit illo nesciunt quas molestias illum exercitationem, optio expedita voluptatum blanditiis, sed, incidunt labore voluptas dolorum porro! Quibusdam mollitia voluptate assumenda qui ducimus cumque, quis esse consequatur laboriosam officia dolorum magnam consequuntur earum unde aut iusto autem! Explicabo dolorem fugiat atque laborum, perferendis beatae commodi optio iste, tempora culpa dignissimos fuga? Rem, minus labore? Maxime harum reiciendis non in voluptatibus vel expedita. Dolore a at harum qui labore, et dolores animi quae molestiae exercitationem. Enim laborum dicta aut officiis incidunt alias mollitia minus eveniet sunt atque explicabo doloremque esse et laboriosam eligendi architecto quidem ad minima cumque, aperiam delectus saepe distinctio. Adipisci!
    
    </div>
  )
}

export default Homepage